sudo: false
language: node_js
node_js:
    - '6'

env:
  global:
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

after_success: npm run deploy
